In [1]:
pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (pyproject.toml): started
  Building wheel for randomuser (pyproject.toml): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5091 sha256=5e21780fbcbdeb87c3aa90fe92046f410cef9fd085a38e2d788e731eba6115a7
  Stored in directory: c:\users\tina.widuri\appdata\local\pip\cache\wheels\be\62\c8\71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Note: you may need to restart the kernel to use updated packages.

In [17]:
from randomuser import RandomUser
import pandas as pd

r=RandomUser()
user_list=r.generate_users(10)
for user in user_list:
    print(f"{user.get_full_name()},{user.get_email()},{user.get_picture()}")

def get_user():
    user_list=[]
    for user in RandomUser.generate_users(10):
        user_list.append({'Name':user.get_full_name(),'Email':user.get_email(),'Pict':user.get_picture()})
    return pd.DataFrame(user_list)
df1=get_user()
df1

Emir Lenes,emir.lenes@example.com,https://randomuser.me/api/portraits/men/87.jpg
German Iglesias,german.iglesias@example.com,https://randomuser.me/api/portraits/men/2.jpg
Luis Medina,luis.medina@example.com,https://randomuser.me/api/portraits/men/39.jpg
Linnea Hakala,linnea.hakala@example.com,https://randomuser.me/api/portraits/women/70.jpg
Siegward Heider,siegward.heider@example.com,https://randomuser.me/api/portraits/men/3.jpg
Zelaine das Neves,zelaine.dasneves@example.com,https://randomuser.me/api/portraits/women/5.jpg
Daniel Pedersen,daniel.pedersen@example.com,https://randomuser.me/api/portraits/men/56.jpg
Alvaro Flores,alvaro.flores@example.com,https://randomuser.me/api/portraits/men/13.jpg
Vanessa Wood,vanessa.wood@example.com,https://randomuser.me/api/portraits/women/19.jpg
Johan Pedersen,johan.pedersen@example.com,https://randomuser.me/api/portraits/men/16.jpg

,Name,Email,Pict
0,Timmothy Dean,timmothy.dean@example.com,https://randomuser.me/api/portraits/men/17.jpg
1,Naomi Edwards,naomi.edwards@example.com,https://randomuser.me/api/portraits/women/88.jpg
2,Charlie Bonnet,charlie.bonnet@example.com,https://randomuser.me/api/portraits/men/34.jpg
3,Morgane Lefebvre,morgane.lefebvre@example.com,https://randomuser.me/api/portraits/women/69.jpg
4,Morgan Schmitt,morgan.schmitt@example.com,https://randomuser.me/api/portraits/men/23.jpg
5,Eetu Kalm,eetu.kalm@example.com,https://randomuser.me/api/portraits/men/36.jpg
6,Xavier Torres,xavier.torres@example.com,https://randomuser.me/api/portraits/men/16.jpg
7,Ryan Pierre,ryan.pierre@example.com,https://randomuser.me/api/portraits/men/85.jpg
8,Madison Wood,madison.wood@example.com,https://randomuser.me/api/portraits/women/72.jpg
9,Ibtisame Knip,ibtisame.knip@example.com,https://randomuser.me/api/portraits/women/7.jpg

In [74]:
#Fruityvice API
import requests
import json

resp=requests.get("https://fruityvice.com/api/fruit/all")
result=json.loads(resp.content)
pd.DataFrame(result)

df=pd.json_normalize(result)
cherry=df.loc[df['name'] == 'Cherry']
print(f"Cherry family {cherry.iloc[0]['family']}, genus {cherry.iloc[0]['genus']}")
banana=df.loc[df['name']=='Banana']
print(f"Banana nutritions calorie {banana.iloc[0]['nutritions.calories']}")

resp=requests.get("https://official-joke-api.appspot.com/jokes/ten")
result=json.loads(resp.content)
pd.DataFrame(result)

Cherry family Rosaceae, genus Prunus
Banana nutritions calorie 96

,type,setup,punchline,id
0,general,What do you call a bee that lives in America?,A USB.,194
1,programming,If you put a million monkeys at a million keyb...,the rest of them will write Perl,26
2,general,Why are mummys scared of vacation?,They're afraid to unwind.,307
3,general,Why did the man run around his bed?,Because he was trying to catch up on his sleep!,335
4,general,Why does a Moon-rock taste better than an Eart...,Because it's a little meteor.,363
5,general,What do you call sad coffee?,Despresso.,62
6,general,How did Darth Vader know what Luke was getting...,He felt his presents.,117
7,general,Bad at golf?,Join the club.,80
8,general,When is a door not a door?,When it's ajar.,287
9,general,What kind of pants do ghosts wear?,Boo jeans.,261